name: "gradio-vllm"
services:
  app:
    build:
      context: .
    image: gradio-vllm
    restart: always
    env_file:
      - .env
    entrypoint:
      - python
      - /app/main.py
    ports:
      - "7861:7860"